apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: redeemer-recovery

resources:
  - namespace.yaml
  - secret.yaml
  - configmap.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - server-deployment.yaml
  - server-service.yaml
  - client-deployment.yaml
  - client-service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: redeemer-recovery
  app.kubernetes.io/managed-by: kustomize
